blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation | 文档
    url: https://docs.ravenhogwarts.top
    about: Find answers in our documentation. | 在文档中查找答案。
  - name: 💬 WeChat Group | 微信讨论群
    url: https://qrcode.ravenhogwarts.top/obsidian
    about: Join our WeChat discussion group. | 加入微信讨论群。
  - name: 💖 Sponsor | 赞助支持
    url: https://ko-fi.com/ravenhogwarts
    about: Support our work by sponsoring. | 通过赞助支持我们的工作。
